[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn -w 1 -k sync --timeout 120 -b 0.0.0.0:$PORT --access-logfile - --error-logfile - --log-level info wsgi:app"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[environments.production]
variables = { PORT = "8080" }
